# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PackageTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=30, verbose_name='\u5305\u540d')),
                ('tag', models.IntegerField(unique=True, verbose_name='\u6807\u7b7e')),
                ('md5', models.CharField(default='', max_length=10000, verbose_name='\u6807\u7b7e')),
            ],
        ),
    ]
