# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 01:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aopsauth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='\u547d\u4ee4\u7ec4')),
                ('command', models.TextField(blank=True, verbose_name='\u7cfb\u7edf\u547d\u4ee4')),
                ('is_allow', models.BooleanField(default=True, verbose_name='\u72b6\u6001')),
                ('user', models.ManyToManyField(related_name='perm_rule', to=settings.AUTH_USER_MODEL)),
                ('user_group', models.ManyToManyField(related_name='perm_rule', to='aopsauth.UserGroup')),
            ],
        ),
        migrations.CreateModel(
            name='PermLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=244, verbose_name='\u7528\u6237')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='\u65f6\u95f4')),
                ('_type', models.CharField(max_length=10, verbose_name='\u7c7b\u578b')),
                ('action', models.CharField(max_length=20, verbose_name='\u52a8\u4f5c')),
                ('action_ip', models.CharField(max_length=15, verbose_name='\u7528\u6237IP')),
                ('content', models.TextField(verbose_name='\u5185\u5bb9')),
            ],
            options={
                'ordering': ['-datetime'],
                'verbose_name_plural': '\u5ba1\u8ba1\u4fe1\u606f\u7ba1\u7406',
                'default_permissions': (),
                'verbose_name': '\u5ba1\u8ba1\u4fe1\u606f',
                'permissions': (('view_message', '\u67e5\u770b\u64cd\u4f5c\u8bb0\u5f55'), ('edit_message', '\u7ba1\u7406\u64cd\u4f5c\u8bb0\u5f55')),
            },
        ),
    ]
